name: Master workflow

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.4
        env:
          POSTGRES_USER: ln
          POSTGRES_PASSWORD: ln
          POSTGRES_DB: php-l3
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v1

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.0

    - name: Setup project
      run: make setup

    - name: Check lint
      run: make lint

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: make test